# Generated by Django 3.2.8 on 2021-11-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20211108_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='featured_image',
            field=models.ImageField(blank=True, default='default-image.png', null=True, upload_to=''),
        ),
    ]
