# Generated by Django 4.0 on 2021-12-25 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_game_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
