# Generated by Django 4.0 on 2021-12-25 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_company_logo_game_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='company_id',
            new_name='company',
        ),
    ]
