# Generated by Django 4.0 on 2021-12-26 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
        ('market', '0007_gamekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamekey',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
